version: '2'
services:
  relion:
    image: relion:gpu
    command: /opt/relion/bin/relion
#    image: psharkey/netbeans-8.1:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1200
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8088:8080"
    networks:
      - x11
networks:
  x11:
